schema_version: 1

context:
  version: "3.0.2"

package:
  name: lda
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lda/lda-${{ version }}.tar.gz
  sha256: 76fc6fbb066b6d1ec0360a1541c5e1c8b69a728666525e72644c4d5332fc778a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - poetry-core
    - cython
    - meson
    - ninja
    - pip
    - numpy
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - lda
        - lda.datasets
        - lda.utils
      pip_check: true

about:
  summary: Topic modeling with latent Dirichlet allocation
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://lda.readthedocs.io/en/latest/
  repository: https://github.com/ariddell/lda/tree/master
  documentation: https://lda.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
